### ISSUE TITLE
incorrect response for  inside function

### ISSUE THREAD

**Issue by Madanian** [rowanwins/point-in-polygon-hao#19]
const coordinate = [
                      [51.65906944711844, 32.644344469605144],
                      [51.643474062027934, 32.64597280574026],
                      [51.6602114368668, 32.658994206590506],
                      [51.64382208072604, 32.65965256535195],
                      [51.65906944711844, 32.644344469605144],
                    ];

          const point = [51.6476999685446, 32.65383784687809]

          const hao = inside(point, coordinate)
          console.log(`hao gives: ${hao}`) 

for this code, the function should returns true but it  returns false! it means the response is incorrect.
samely I have this bug when I use turf.booleanPointInPolygon
do you have any suggestion for me? it is very important for me

**Comment by rowanwins** [comment]
Hi @Madanian 

So it looks like the polygon you've provided contains self-intersections.
<img width="1390" alt="geojson io | powered by Mapbox 2024-02-19 19-46-55" src="https://github.com/rowanwins/point-in-polygon-hao/assets/6735870/275b8b46-0215-48c4-9690-ed53c6eb840b">

In theory this algorithm is supposed to work with those sorts of polygons but it doesn't appear to be working in this case - not sure why sorry.

Regards,
Rowan

**Comment by jjrv** [comment]
Just in case I'm copying this reply:
https://github.com/mikolalysenko/robust-point-in-polygon/issues/2#issuecomment-2492297802
also here:

I'm not a mathematician, but I'd guess the paper describes a robust algorithm. Your implementation contains calculations like:
```
f = (u1 * v2) - (u2 * v1)
```
where u1, u2, v1, v2 are subtraction results.

Those are prone to reporting an incorrect sign due to rounding errors. `robust-predicates` was specifically designed to correctly compute the sign of `(ax - cx) * (by - cy) - (ay - cy) * (bx - cx)`. It takes about a hundred lines of code to do so.

The paper is written assuming infinite precision, it doesn't go into low-level details how to do floating point math on computers (or maybe they didn't test pathological cases, but if that's the only reason it fails, this should be the part that needs fixing).

After investigating this further, I think algorithm 7 in "The Point in Polygon Problem for Arbitrary Polygons" by Kai Hormann and Alexander Agathos might handle rounding issues correctly while minimizing the need for robust predicates. For some reason the paper by Hao and Sun claims it contains bugs and theirs is more robust, but I'm not convinced.

They write:
> Despite many efforts [2,4], these approaches have the same problems as previous algorithms with
degenerate cases (see Figure 1g). A detailed theoretical analysis and the proof of the correctness of
the method for the point-in-polygon test are missing. In addition, apart from [4–6], few algorithms
do not need to perform calculations for intersection points and costly division operations. However,
these algorithms overlook some problems, such as how to identify a point lying on ∂S and apply the
point-in-polygon test for a polygon containing nested holes, as shown in Figure 3a. No attempt to
optimize the algorithms for computing speed has been done.

Reference 2 is the paper by Hormann and Agathos. I'm not qualified to assess their proofs of correctness but one thing is clear: that paper has taken an extensive effort to optimize the algorithms for computing speed. Also, it does not perform division operations, and talks at length about identifying points lying on ∂S.

**Comment by jjrv** [comment]
As for the coordinates and point reported in this thread, the point is clearly outside and `false` is the correct result! It's very clear in that image you posted and even clearer here (Y axis is flipped compared to the map since I took the numbers as screen X/Y coordinates instead of lon/lat):
![outside-ribbon](https://github.com/user-attachments/assets/d6b5c4d3-36e8-4d4b-8f2d-d43307bdbb6f)

**Comment by rowanwins** [comment]
Hi @Madanian , I've just released v1.2.0 which incorporate the robust-predicates library and seems to be helping in some scenarios (eg https://github.com/mikolalysenko/robust-point-in-polygon/issues/2#issuecomment-1373038489).
